import type { SiteSettings } from '../types'

export const defaultSiteSettings: SiteSettings = {
  about_badges: '',
  about_blog_section_body: '',
  about_blog_section_title: 'What This Blog Covers',
  about_contact_body: '',
  about_contact_title: 'Say Hello',
  about_hero_title: 'About',
  about_story_body: '',
  about_travel_pattern_stat_1_text: '',
  about_travel_pattern_stat_1_value: '',
  about_travel_pattern_stat_2_text: '',
  about_travel_pattern_stat_2_value: '',
  about_travel_pattern_stat_3_text: '',
  about_travel_pattern_stat_3_value: '',
  about_travel_pattern_title: 'Travel Pattern',
  about_travel_style_body: '',
  about_travel_style_title: 'How I Travel',
  author_bio: '',
  author_initials: 'JT',
  author_name: 'Julia',
  contact_background_image_url: '',
  contact_email: '',
  contact_form_intro: '',
  contact_form_title: 'Write To Julia',
  contact_hero_body: '',
  contact_hero_eyebrow: 'Contact',
  contact_hero_title: 'Get in touch',
  contact_sidebar_body: '',
  contact_sidebar_title: 'Other Ways To Reach Me',
  contact_tips: '',
  hero_eyebrow: '',
  hero_subtitle: '',
  hero_title: 'Misadventures in Germany',
  instagram_url: '',
  singleton: true,
  updated_at: '',
  youtube_url: '',
}
